<?php

use App\Models\Tipo;
use App\Models\TipoAtencion;
use App\Models\TipoEstadoCaja;
use App\Models\TipoFirma;
use App\Models\Institucion;
use App\Models\Provincia;
use App\Models\Canton;
use App\Models\ConfiguracionValidacion;
use App\Models\EstadoTramite;
use App\Models\Parroquia;
use App\Models\TipoDocumento;
use App\Models\TipoIngreso;
use App\Models\TipoTramite;
use Illuminate\Database\Seeder;

class ListaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        
        /*// Tipos
        $Tipos = ['INGRESO','DEVOLUCIÓN','RE-INGRESO','OBJECIÓN','EXTEMPORANEO'];
        foreach ($Tipos as $value) {
            Tipo::create(['nombre' => $value]);
        }

        // Tipos atencion
        $TiposAtencion = ['AMBULATORIO','EMERGENCIA','PRE-HOSPITALARIA','HOSPITALIZACIÓN','HOSPITAL DEL DÍA'];
        foreach ($TiposAtencion as $value) {
            TipoAtencion::create(['nombre' => $value]);
        }

        // Tipos estados caja
        $TiposEstadoCaja = ['ABIERTA','CERRADA'];
        foreach ($TiposEstadoCaja as $value) {
            TipoEstadoCaja::create(['nombre' => $value]);
        }

        // Tipos firma
        $TiposFirma = ['FIRMA MANUAL','FIRMA ELECTRÓNICA','FIRMADO ELECTRONICAMENTE','NO APLICA'];
        foreach ($TiposFirma as $value) {
            TipoFirma::create(['nombre' => $value]);
        }

        // Tipos ingreso
        $TiposIngreso = ['PRESTADOR','COURIER'];
        foreach ($TiposIngreso as $value) {
            TipoIngreso::create(['nombre' => $value]);
        }

        // Tipos documento
        $TiposDocumento = ['PLANILLAJE'];
        foreach ($TiposDocumento as $value) {
            TipoDocumento::create(['nombre' => $value]);
        }

        // Tipos tramite
        $TiposTramite = ['NORMAL','REZAGADO','REZAGADO LEVANTAMIENTO DE OBJECIONES','EXTEMPORANEOS'];
        foreach ($TiposTramite as $value) {
            TipoTramite::create(['nombre' => $value]);
        }

        // Instituciones
        $Instituciones = ['PÚBLICA','PRIVADA'];
        foreach ($Instituciones as $value) {
            Institucion::create(['nombre' => $value]);
        }

        // Configuración validación
        $validaciones = ['CONTROL VALIDACIÓN POR PRESTADOR, TIPO DE ATENCIÓN Y FECHA DE SERVICIO'];
        foreach ($validaciones as $validacion) {
            ConfiguracionValidacion::create(['validacion' => $validacion]);
        }

        // Estados tramite
        $EstadosTramite = ['INGRESO','ENVIO AUDITORIA','DEVOLUCION AUDITORIA','DEVOLUCION PRESTADOR'];
        foreach ($EstadosTramite as $value) {
            EstadoTramite::create(['nombre' => $value]);
        }

        // Provincias
        $Provincias = ['AZUAY','BOLIVAR','CAÑAR','CARCHI','COTOPAXI','CHIMBORAZO','EL ORO','ESMERALDAS','GUAYAS','IMBABURA','LOJA','LOS RIOS','MANABI','MORONA SANTIAGO','NAPO','PASTAZA','PICHINCHA','TUNGURAHUA','ZAMORA CHINCHIPE','GALAPAGOS','SUCUMBIOS','ORELLANA','SANTO DOMINGO DE LOS TSACHILAS','SANTA ELENA'];
        foreach ($Provincias as $value) {
            Provincia::create(['nombre' => $value]);
        }

        // Cantones
        $Cantones = [
            ['1','CUENCA'],
            ['1','GIRÓN'],
            ['1','GUALACEO'],
            ['1','NABÓN'],
            ['1','PAUTE'],
            ['1','PUCARA'],
            ['1','SAN FERNANDO'],
            ['1','SANTA ISABEL'],
            ['1','SIGSIG'],
            ['1','OÑA'],
            ['1','CHORDELEG'],
            ['1','EL PAN'],
            ['1','SEVILLA DE ORO'],
            ['1','GUACHAPALA'],
            ['1','CAMILO PONCE ENRÍQUEZ'],
            ['2','GUARANDA'],
            ['2','CHILLANES'],
            ['2','CHIMBO'],
            ['2','ECHEANDÍA'],
            ['2','SAN MIGUEL'],
            ['2','CALUMA'],
            ['2','LAS NAVES'],
            ['3','AZOGUES'],
            ['3','BIBLIÁN'],
            ['3','CAÑAR'],
            ['3','LA TRONCAL'],
            ['3','EL TAMBO'],
            ['3','DÉLEG'],
            ['3','SUSCAL'],
            ['4','TULCÁN'],
            ['4','BOLÍVAR'],
            ['4','ESPEJO'],
            ['4','MIRA'],
            ['4','MONTÚFAR'],
            ['4','SAN PEDRO DE HUACA'],
            ['5','LATACUNGA'],
            ['5','LA MANÁ'],
            ['5','PANGUA'],
            ['5','PUJILI'],
            ['5','SALCEDO'],
            ['5','SAQUISILÍ'],
            ['5','SIGCHOS'],
            ['6','RIOBAMBA'],
            ['6','ALAUSI'],
            ['6','COLTA'],
            ['6','CHAMBO'],
            ['6','CHUNCHI'],
            ['6','GUAMOTE'],
            ['6','GUANO'],
            ['6','PALLATANGA'],
            ['6','PENIPE'],
            ['6','CUMANDÁ'],
            ['7','MACHALA'],
            ['7','ARENILLAS'],
            ['7','ATAHUALPA'],
            ['7','BALSAS'],
            ['7','CHILLA'],
            ['7','EL GUABO'],
            ['7','HUAQUILLAS'],
            ['7','MARCABELÍ'],
            ['7','PASAJE'],
            ['7','PIÑAS'],
            ['7','PORTOVELO'],
            ['7','SANTA ROSA'],
            ['7','ZARUMA'],
            ['7','LAS LAJAS'],
            ['8','ESMERALDAS'],
            ['8','ELOY ALFARO'],
            ['8','MUISNE'],
            ['8','QUININDÉ'],
            ['8','SAN LORENZO'],
            ['8','ATACAMES'],
            ['8','RIOVERDE'],
            ['8','LA CONCORDIA'],
            ['9','GUAYAQUIL'],
            ['9','ALFREDO BAQUERIZO MORENO (JUJÁN)'],
            ['9','BALAO'],
            ['9','BALZAR'],
            ['9','COLIMES'],
            ['9','DAULE'],
            ['9','DURÁN'],
            ['9','EL EMPALME'],
            ['9','EL TRIUNFO'],
            ['9','MILAGRO'],
            ['9','NARANJAL'],
            ['9','NARANJITO'],
            ['9','PALESTINA'],
            ['9','PEDRO CARBO'],
            ['9','SAMBORONDÓN'],
            ['9','SANTA LUCÍA'],
            ['9','SALITRE (URBINA JADO)'],
            ['9','SAN JACINTO DE YAGUACHI'],
            ['9','PLAYAS'],
            ['9','SIMÓN BOLÍVAR'],
            ['9','ORONEL MARCELINO MARIDUE'],
            ['9','LOMAS DE SARGENTILLO'],
            ['9','NOBOL'],
            ['9','GENERAL ANTONIO ELIZALDE'],
            ['9','ISIDRO AYORA'],
            ['10','IBARRA'],
            ['10','ANTONIO ANTE'],
            ['10','COTACACHI'],
            ['10','OTAVALO'],
            ['10','PIMAMPIRO'],
            ['10','SAN MIGUEL DE URCUQUÍ'],
            ['11','LOJA'],
            ['11','CALVAS'],
            ['11','CATAMAYO'],
            ['11','CELICA'],
            ['11','CHAGUARPAMBA'],
            ['11','ESPÍNDOLA'],
            ['11','GONZANAMÁ'],
            ['11','MACARÁ'],
            ['11','PALTAS'],
            ['11','PUYANGO'],
            ['11','SARAGURO'],
            ['11','SOZORANGA'],
            ['11','ZAPOTILLO'],
            ['11','PINDAL'],
            ['11','QUILANGA'],
            ['11','OLMEDO'],
            ['12','BABAHOYO'],
            ['12','BABA'],
            ['12','MONTALVO'],
            ['12','PUEBLOVIEJO'],
            ['12','QUEVEDO'],
            ['12','URDANETA'],
            ['12','VENTANAS'],
            ['12','VÍNCES'],
            ['12','PALENQUE'],
            ['12','BUENA FÉ'],
            ['12','VALENCIA'],
            ['12','MOCACHE'],
            ['12','QUINSALOMA'],
            ['13','PORTOVIEJO'],
            ['13','BOLÍVAR'],
            ['13','CHONE'],
            ['13','EL CARMEN'],
            ['13','FLAVIO ALFARO'],
            ['13','JIPIJAPA'],
            ['13','JUNÍN'],
            ['13','MANTA'],
            ['13','MONTECRISTI'],
            ['13','PAJÁN'],
            ['13','PICHINCHA'],
            ['13','ROCAFUERTE'],
            ['13','SANTA ANA'],
            ['13','SUCRE'],
            ['13','TOSAGUA'],
            ['13','24 DE MAYO'],
            ['13','PEDERNALES'],
            ['13','OLMEDO'],
            ['13','PUERTO LÓPEZ'],
            ['13','JAMA'],
            ['13','JARAMIJÓ'],
            ['13','SAN VICENTE'],
            ['14','MORONA'],
            ['14','GUALAQUIZA'],
            ['14','LIMÓN INDANZA'],
            ['14','PALORA'],
            ['14','SANTIAGO'],
            ['14','SUCÚA'],
            ['14','HUAMBOYA'],
            ['14','SAN JUAN BOSCO'],
            ['14','TAISHA'],
            ['14','LOGROÑO'],
            ['14','PABLO SEXTO'],
            ['14','TIWINTZA'],
            ['15','TENA'],
            ['15','ARCHIDONA'],
            ['15','EL CHACO'],
            ['15','QUIJOS'],
            ['15','CARLOS JULIO AROSEMENA TOL'],
            ['16','PASTAZA'],
            ['16','MERA'],
            ['16','SANTA CLARA'],
            ['16','ARAJUNO'],
            ['17','QUITO'],
            ['17','CAYAMBE'],
            ['17','MEJIA'],
            ['17','PEDRO MONCAYO'],
            ['17','RUMIÑAHUI'],
            ['17','SAN MIGUEL DE LOS BANCOS'],
            ['17','PEDRO VICENTE MALDONADO'],
            ['17','PUERTO QUITO'],
            ['18','AMBATO'],
            ['18','BAÑOS DE AGUA SANTA'],
            ['18','CEVALLOS'],
            ['18','MOCHA'],
            ['18','PATATE'],
            ['18','QUERO'],
            ['18','SAN PEDRO DE PELILEO'],
            ['18','SANTIAGO DE PÍLLARO'],
            ['18','TISALEO'],
            ['19','ZAMORA'],
            ['19','CHINCHIPE'],
            ['19','NANGARITZA'],
            ['19','YACUAMBI'],
            ['19','YANTZAZA (YANZATZA)'],
            ['19','EL PANGUI'],
            ['19','CENTINELA DEL CÓNDOR'],
            ['19','PALANDA'],
            ['19','PAQUISHA'],
            ['20','SAN CRISTÓBAL'],
            ['20','ISABELA'],
            ['20','SANTA CRUZ'],
            ['21','LAGO AGRIO'],
            ['21','GONZALO PIZARRO'],
            ['21','PUTUMAYO'],
            ['21','SHUSHUFINDI'],
            ['21','SUCUMBÍOS'],
            ['21','CASCALES'],
            ['21','CUYABENO'],
            ['22','ORELLANA'],
            ['22','AGUARICO'],
            ['22','LA JOYA DE LOS SACHAS'],
            ['22','LORETO'],
            ['23','SANTO DOMINGO'],
            ['24','SANTA ELENA'],
            ['24','LA LIBERTAD'],
            ['24','SALINAS']
        ];

        foreach ($Cantones as $value) {
            Canton::create(['provincia_id' => $value[0],'nombre' => $value[1]]);
        }

        // Parroquias
        $Parroquias = [
            ['1','1','BELLAVISTA'],
            ['1','1','CAÑARIBAMBA'],
            ['1','1','EL BATÁN'],
            ['1','1','EL SAGRARIO'],
            ['1','1','EL VECINO'],
            ['1','1','GIL RAMÍREZ DÁVALOS'],
            ['1','1','HUAYNACÁPAC'],
            ['1','1','MACHÁNGARA'],
            ['1','1','MONAY'],
            ['1','1','SAN BLAS'],
            ['1','1','SAN SEBASTIÁN'],
            ['1','1','SUCRE'],
            ['1','1','TOTORACOCHA'],
            ['1','1','YANUNCAY'],
            ['1','1','HERMANO MIGUEL'],
            ['1','1','CUENCA'],
            ['1','1','BAÑOS'],
            ['1','1','CUMBE'],
            ['1','1','CHAUCHA'],
            ['1','1','CHECA (JIDCAY)'],
            ['1','1','CHIQUINTAD'],
            ['1','1','LLACAO'],
            ['1','1','MOLLETURO'],
            ['1','1','NULTI'],
            ['1','1','OCTAVIO CORDERO PALACIOS (SANTA ROSA)'],
            ['1','1','PACCHA'],
            ['1','1','QUINGEO'],
            ['1','1','RICAURTE'],
            ['1','1','SAN JOAQUÍN'],
            ['1','1','SANTA ANA'],
            ['1','1','SAYAUSÍ'],
            ['1','1','SIDCAY'],
            ['1','1','SININCAY'],
            ['1','1','TARQUI'],
            ['1','1','TURI'],
            ['1','1','VALLE'],
            ['1','1','VICTORIA DEL PORTETE (IRQUIS)'],
            ['1','2','GIRÓN'],
            ['1','2','ASUNCIÓN'],
            ['1','2','SAN GERARDO'],
            ['1','3','GUALACEO'],
            ['1','3','CHORDELEG'],
            ['1','3','DANIEL CÓRDOVA TORAL (EL ORIENTE)'],
            ['1','3','JADÁN'],
            ['1','3','MARIANO MORENO'],
            ['1','3','PRINCIPAL'],
            ['1','3','REMIGIO CRESPO TORAL (GÚLAG)'],
            ['1','3','SAN JUAN'],
            ['1','3','ZHIDMAD'],
            ['1','3','LUIS CORDERO VEGA'],
            ['1','3','SIMÓN BOLÍVAR (CAB. EN GAÑANZOL)'],
            ['1','4','NABÓN'],
            ['1','4','COCHAPATA'],
            ['1','4','EL PROGRESO (CAB.EN ZHOTA)'],
            ['1','4','LAS NIEVES (CHAYA)'],
            ['1','4','OÑA'],
            ['1','5','PAUTE'],
            ['1','5','AMALUZA'],
            ['1','5','BULÁN (JOSÉ VÍCTOR IZQUIERDO)'],
            ['1','5','CHICÁN (GUILLERMO ORTEGA)'],
            ['1','5','EL CABO'],
            ['1','5','GUACHAPALA'],
            ['1','5','GUARAINAG'],
            ['1','5','PALMAS'],
            ['1','5','PAN'],
            ['1','5','SAN CRISTÓBAL (CARLOS ORDÓÑEZ LAZO)'],
            ['1','5','SEVILLA DE ORO'],
            ['1','5','TOMEBAMBA'],
            ['1','5','DUG DUG'],
            ['1','6','PUCARÁ'],
            ['1','6','CAMILO PONCE ENRÍQUEZ (CAB. EN RÍO 7 DE MOLLEPONGO'],
            ['1','6','SAN RAFAEL DE SHARUG'],
            ['1','7','SAN FERNANDO'],
            ['1','7','CHUMBLÍN'],
            ['1','8','SANTA ISABEL (CHAGUARURCO)'],
            ['1','8','ABDÓN CALDERÓN (LA UNIÓN)'],
            ['1','8','EL CARMEN DE PIJILÍ'],
            ['1','8','ZHAGLLI (SHAGLLI)'],
            ['1','8','SAN SALVADOR DE CAÑARIBAMBA'],
            ['1','9','SIGSIG'],
            ['1','9','CUCHIL (CUTCHIL)'],
            ['1','9','GIMA'],
            ['1','9','GUEL'],
            ['1','9','LUDO'],
            ['1','9','SAN BARTOLOMÉ'],
            ['1','9','SAN JOSÉ DE RARANGA'],
            ['1','10','SAN FELIPE DE OÑA CABECERA CANTONAL'],
            ['1','10','SUSUDEL'],
            ['1','11','CHORDELEG'],
            ['1','11','PRINCIPAL'],
            ['1','11','LA UNIÓN'],
            ['1','11','LUIS GALARZA ORELLANA (CAB.EN DELEGSOL)'],
            ['1','11','SAN MARTÍN DE PUZHIO'],
            ['1','12','EL PAN'],
            ['1','12','AMALUZA'],
            ['1','12','PALMAS'],
            ['1','12','SAN VICENTE'],
            ['1','13','SEVILLA DE ORO'],
            ['1','13','AMALUZA'],
            ['1','13','PALMAS'],
            ['1','14','GUACHAPALA'],
            ['1','15','CAMILO PONCE ENRÍQUEZ'],
            ['1','15','EL CARMEN DE PIJILÍ'],
            ['2','16','ÁNGEL POLIBIO CHÁVES'],
            ['2','16','GABRIEL IGNACIO VEINTIMILLA'],
            ['2','16','GUANUJO'],
            ['2','16','GUARANDA'],
            ['2','16','FACUNDO VELA'],
            ['2','16','JULIO E. MORENO (CATANAHUÁN GRANDE)'],
            ['2','16','LAS NAVES'],
            ['2','16','SALINAS'],
            ['2','16','SAN LORENZO'],
            ['2','16','SAN SIMÓN (YACOTO)'],
            ['2','16','SANTA FÉ (SANTA FÉ)'],
            ['2','16','SIMIÁTUG'],
            ['2','16','SAN LUIS DE PAMBIL'],
            ['2','17','CHILLANES'],
            ['2','17','SAN JOSÉ DEL TAMBO (TAMBOPAMBA)'],
            ['2','18','SAN JOSÉ DE CHIMBO'],
            ['2','18','ASUNCIÓN (ASANCOTO)'],
            ['2','18','CALUMA'],
            ['2','18','MAGDALENA (CHAPACOTO)'],
            ['2','18','SAN SEBASTIÁN'],
            ['2','18','TELIMBELA'],
            ['2','19','ECHEANDÍA'],
            ['2','20','SAN MIGUEL'],
            ['2','20','BALSAPAMBA'],
            ['2','20','BILOVÁN'],
            ['2','20','RÉGULO DE MORA'],
            ['2','20','SAN PABLO (SAN PABLO DE ATENAS)'],
            ['2','20','SANTIAGO'],
            ['2','20','SAN VICENTE'],
            ['2','21','CALUMA'],
            ['2','22','LAS MERCEDES'],
            ['2','22','LAS NAVES'],
            ['3','23','AURELIO BAYAS MARTÍNEZ'],
            ['3','23','AZOGUES'],
            ['3','23','BORRERO'],
            ['3','23','SAN FRANCISCO'],
            ['3','23','COJITAMBO'],
            ['3','23','DÉLEG'],
            ['3','23','GUAPÁN'],
            ['3','23','JAVIER LOYOLA (CHUQUIPATA)'],
            ['3','23','LUIS CORDERO'],
            ['3','23','PINDILIG'],
            ['3','23','RIVERA'],
            ['3','23','SAN MIGUEL'],
            ['3','23','SOLANO'],
            ['3','23','TADAY'],
            ['3','24','BIBLIÁN'],
            ['3','24','NAZÓN (CAB. EN PAMPA DE DOMÍNGUEZ)'],
            ['3','24','SAN FRANCISCO DE SAGEO'],
            ['3','24','TURUPAMBA'],
            ['3','24','JERUSALÉN'],
            ['3','25','CAÑAR'],
            ['3','25','CHONTAMARCA'],
            ['3','25','CHOROCOPTE'],
            ['3','25','GENERAL MORALES (SOCARTE)'],
            ['3','25','GUALLETURO'],
            ['3','25','HONORATO VÁSQUEZ (TAMBO VIEJO)'],
            ['3','25','INGAPIRCA'],
            ['3','25','JUNCAL'],
            ['3','25','SAN ANTONIO'],
            ['3','25','SUSCAL'],
            ['3','25','TAMBO'],
            ['3','25','ZHUD'],
            ['3','25','VENTURA'],
            ['3','25','DUCUR'],
            ['3','26','LA TRONCAL'],
            ['3','26','MANUEL J. CALLE'],
            ['3','26','PANCHO NEGRO'],
            ['3','27','EL TAMBO'],
            ['3','28','DÉLEG'],
            ['3','28','SOLANO'],
            ['3','29','SUSCAL'],
            ['4','30','GONZÁLEZ SUÁREZ'],
            ['4','30','TULCÁN'],
            ['4','30','EL CARMELO (EL PUN)'],
            ['4','30','HUACA'],
            ['4','30','JULIO ANDRADE (OREJUELA)'],
            ['4','30','MALDONADO'],
            ['4','30','PIOTER'],
            ['4','30','TOBAR DONOSO (LA BOCANA DE CAMUMBÍ)'],
            ['4','30','TUFIÑO'],
            ['4','30','URBINA (TAYA)'],
            ['4','30','EL CHICAL'],
            ['4','30','MARISCAL SUCRE'],
            ['4','30','SANTA MARTHA DE CUBA'],
            ['4','31','BOLÍVAR'],
            ['4','31','GARCÍA MORENO'],
            ['4','31','LOS ANDES'],
            ['4','31','MONTE OLIVO'],
            ['4','31','SAN VICENTE DE PUSIR'],
            ['4','31','SAN RAFAEL'],
            ['4','32','EL ÁNGEL'],
            ['4','32','27 DE SEPTIEMBRE'],
            ['4','32','EL ANGEL'],
            ['4','32','EL GOALTAL'],
            ['4','32','LA LIBERTAD (ALIZO)'],
            ['4','32','SAN ISIDRO'],
            ['4','33','MIRA (CHONTAHUASI)'],
            ['4','33','CONCEPCIÓN'],
            ['4','33','JIJÓN Y CAAMAÑO (CAB. EN RÍO BLANCO)'],
            ['4','33','JUAN MONTALVO (SAN IGNACIO DE QUIL)'],
            ['4','34','GONZÁLEZ SUÁREZ'],
            ['4','34','SAN JOSÉ'],
            ['4','34','SAN GABRIEL'],
            ['4','34','CRISTÓBAL COLÓN'],
            ['4','34','CHITÁN DE NAVARRETE'],
            ['4','34','FERNÁNDEZ SALVADOR'],
            ['4','34','LA PAZ'],
            ['4','34','PIARTAL'],
            ['4','35','HUACA'],
            ['4','35','MARISCAL SUCRE'],
            ['5','36','ELOY ALFARO (SAN FELIPE)'],
            ['5','36','IGNACIO FLORES (PARQUE FLORES)'],
            ['5','36','JUAN MONTALVO (SAN SEBASTIÁN)'],
            ['5','36','LA MATRIZ'],
            ['5','36','SAN BUENAVENTURA'],
            ['5','36','LATACUNGA'],
            ['5','36','ALAQUES (ALÁQUEZ)'],
            ['5','36','BELISARIO QUEVEDO (GUANAILÍN)'],
            ['5','36','GUAITACAMA (GUAYTACAMA)'],
            ['5','36','JOSEGUANGO BAJO'],
            ['5','36','LAS PAMPAS'],
            ['5','36','MULALÓ'],
            ['5','36','11 DE NOVIEMBRE (ILINCHISI)'],
            ['5','36','POALÓ'],
            ['5','36','SAN JUAN DE PASTOCALLE'],
            ['5','36','SIGCHOS'],
            ['5','36','TANICUCHÍ'],
            ['5','36','TOACASO'],
            ['5','36','PALO QUEMADO'],
            ['5','37','EL CARMEN'],
            ['5','37','LA MANÁ'],
            ['5','37','EL TRIUNFO'],
            ['5','37','GUASAGANDA (CAB.EN GUASAGANDA'],
            ['5','37','PUCAYACU'],
            ['5','38','EL CORAZÓN'],
            ['5','38','MORASPUNGO'],
            ['5','38','PINLLOPATA'],
            ['5','38','RAMÓN CAMPAÑA'],
            ['5','39','PUJILÍ'],
            ['5','39','ANGAMARCA'],
            ['5','39','CHUCCHILÁN (CHUGCHILÁN)'],
            ['5','39','GUANGAJE'],
            ['5','39','ISINLIBÍ (ISINLIVÍ)'],
            ['5','39','LA VICTORIA'],
            ['5','39','PILALÓ'],
            ['5','39','TINGO'],
            ['5','39','ZUMBAHUA'],
            ['5','40','SAN MIGUEL'],
            ['5','40','ANTONIO JOSÉ HOLGUÍN (SANTA LUCÍA)'],
            ['5','40','CUSUBAMBA'],
            ['5','40','MULALILLO'],
            ['5','40','MULLIQUINDIL (SANTA ANA)'],
            ['5','40','PANSALEO'],
            ['5','41','SAQUISILÍ'],
            ['5','41','CANCHAGUA'],
            ['5','41','CHANTILÍN'],
            ['5','41','COCHAPAMBA'],
            ['5','42','SIGCHOS'],
            ['5','42','CHUGCHILLÁN'],
            ['5','42','ISINLIVÍ'],
            ['5','42','LAS PAMPAS'],
            ['5','42','PALO QUEMADO'],
            ['6','43','LIZARZABURU'],
            ['6','43','MALDONADO'],
            ['6','43','VELASCO'],
            ['6','43','VELOZ'],
            ['6','43','YARUQUÍES'],
            ['6','43','RIOBAMBA'],
            ['6','43','CACHA (CAB. EN MACHÁNGARA)'],
            ['6','43','CALPI'],
            ['6','43','CUBIJÍES'],
            ['6','43','FLORES'],
            ['6','43','LICÁN'],
            ['6','43','LICTO'],
            ['6','43','PUNGALÁ'],
            ['6','43','PUNÍN'],
            ['6','43','QUIMIAG'],
            ['6','43','SAN JUAN'],
            ['6','43','SAN LUIS'],
            ['6','44','ALAUSÍ'],
            ['6','44','ACHUPALLAS'],
            ['6','44','CUMANDÁ'],
            ['6','44','GUASUNTOS'],
            ['6','44','HUIGRA'],
            ['6','44','MULTITUD'],
            ['6','44','PISTISHÍ (NARIZ DEL DIABLO)'],
            ['6','44','PUMALLACTA'],
            ['6','44','SEVILLA'],
            ['6','44','SIBAMBE'],
            ['6','44','TIXÁN'],
            ['6','45','CAJABAMBA'],
            ['6','45','SICALPA'],
            ['6','45','VILLA LA UNIÓN (CAJABAMBA)'],
            ['6','45','CAÑI'],
            ['6','45','COLUMBE'],
            ['6','45','JUAN DE VELASCO (PANGOR)'],
            ['6','45','SANTIAGO DE QUITO (CAB. EN SAN ANTONIO DE QUITO)'],
            ['6','46','CHAMBO'],
            ['6','47','CHUNCHI'],
            ['6','47','CAPZOL'],
            ['6','47','COMPUD'],
            ['6','47','GONZOL'],
            ['6','47','LLAGOS'],
            ['6','48','GUAMOTE'],
            ['6','48','CEBADAS'],
            ['6','48','PALMIRA'],
            ['6','49','EL ROSARIO'],
            ['6','49','LA MATRIZ'],
            ['6','49','GUANO'],
            ['6','49','GUANANDO'],
            ['6','49','ILAPO'],
            ['6','49','LA PROVIDENCIA'],
            ['6','49','SAN ANDRÉS'],
            ['6','49','SAN GERARDO DE PACAICAGUÁN'],
            ['6','49','SAN ISIDRO DE PATULÚ'],
            ['6','49','SAN JOSÉ DEL CHAZO'],
            ['6','49','SANTA FÉ DE GALÁN'],
            ['6','49','VALPARAÍSO'],
            ['6','50','PALLATANGA'],
            ['6','51','PENIPE'],
            ['6','51','EL ALTAR'],
            ['6','51','MATUS'],
            ['6','51','PUELA'],
            ['6','51','SAN ANTONIO DE BAYUSHIG'],
            ['6','51','LA CANDELARIA'],
            ['6','51','BILBAO (CAB.EN QUILLUYACU)'],
            ['6','52','CUMANDÁ'],
            ['7','53','LA PROVIDENCIA'],
            ['7','53','MACHALA'],
            ['7','53','PUERTO BOLÍVAR'],
            ['7','53','NUEVE DE MAYO'],
            ['7','53','EL CAMBIO'],
            ['7','53','EL RETIRO'],
            ['7','54','ARENILLAS'],
            ['7','54','CHACRAS'],
            ['7','54','LA LIBERTAD'],
            ['7','54','LAS LAJAS (CAB. EN LA VICTORIA)'],
            ['7','54','PALMALES'],
            ['7','54','CARCABÓN'],
            ['7','55','PACCHA'],
            ['7','55','AYAPAMBA'],
            ['7','55','CORDONCILLO'],
            ['7','55','MILAGRO'],
            ['7','55','SAN JOSÉ'],
            ['7','55','SAN JUAN DE CERRO AZUL'],
            ['7','56','BALSAS'],
            ['7','56','BELLAMARÍA'],
            ['7','57','CHILLA'],
            ['7','58','EL GUABO'],
            ['7','58','BARBONES (SUCRE)'],
            ['7','58','LA IBERIA'],
            ['7','58','TENDALES (CAB.EN PUERTO TENDALES)'],
            ['7','58','RÍO BONITO'],
            ['7','59','ECUADOR'],
            ['7','59','EL PARAÍSO'],
            ['7','59','HUALTACO'],
            ['7','59','MILTON REYES'],
            ['7','59','UNIÓN LOJANA'],
            ['7','59','HUAQUILLAS'],
            ['7','60','MARCABELÍ'],
            ['7','60','EL INGENIO'],
            ['7','61','BOLÍVAR'],
            ['7','61','LOMA DE FRANCO'],
            ['7','61','OCHOA LEÓN (MATRIZ)'],
            ['7','61','TRES CERRITOS'],
            ['7','61','PASAJE'],
            ['7','61','BUENAVISTA'],
            ['7','61','CASACAY'],
            ['7','61','LA PEAÑA'],
            ['7','61','PROGRESO'],
            ['7','61','UZHCURRUMI'],
            ['7','61','CAÑAQUEMADA'],
            ['7','62','LA MATRIZ'],
            ['7','62','LA SUSAYA'],
            ['7','62','PIÑAS GRANDE'],
            ['7','62','PIÑAS'],
            ['7','62','CAPIRO (CAB. EN LA CAPILLA DE CAPIRO)'],
            ['7','62','LA BOCANA'],
            ['7','62','MOROMORO (CAB. EN EL VADO)'],
            ['7','62','PIEDRAS'],
            ['7','62','SAN ROQUE (AMBROSIO MALDONADO)'],
            ['7','62','SARACAY'],
            ['7','63','PORTOVELO'],
            ['7','63','CURTINCAPA'],
            ['7','63','MORALES'],
            ['7','63','SALATÍ'],
            ['7','64','SANTA ROSA'],
            ['7','64','PUERTO JELÍ'],
            ['7','64','BALNEARIO JAMBELÍ (SATÉLITE)'],
            ['7','64','JUMÓN (SATÉLITE)'],
            ['7','64','NUEVO SANTA ROSA'],
            ['7','64','BELLAVISTA'],
            ['7','64','JAMBELÍ'],
            ['7','64','LA AVANZADA'],
            ['7','64','SAN ANTONIO'],
            ['7','64','TORATA'],
            ['7','64','VICTORIA'],
            ['7','64','BELLAMARÍA'],
            ['7','65','ZARUMA'],
            ['7','65','ABAÑÍN'],
            ['7','65','ARCAPAMBA'],
            ['7','65','GUANAZÁN'],
            ['7','65','GUIZHAGUIÑA'],
            ['7','65','HUERTAS'],
            ['7','65','MALVAS'],
            ['7','65','MULUNCAY GRANDE'],
            ['7','65','SINSAO'],
            ['7','65','SALVIAS'],
            ['7','66','LA VICTORIA'],
            ['7','66','PLATANILLOS'],
            ['7','66','VALLE HERMOSO'],
            ['7','66','LA LIBERTAD'],
            ['7','66','EL PARAÍSO'],
            ['7','66','SAN ISIDRO'],
            ['8','67','BARTOLOMÉ RUIZ (CÉSAR FRANCO CARRIÓN)'],
            ['8','67','5 DE AGOSTO'],
            ['8','67','ESMERALDAS'],
            ['8','67','LUIS TELLO (LAS PALMAS)'],
            ['8','67','SIMÓN PLATA TORRES'],
            ['8','67','ATACAMES'],
            ['8','67','CAMARONES (CAB. EN SAN VICENTE)'],
            ['8','67','CRNEL. CARLOS CONCHA TORRES (CAB.EN HUELE)'],
            ['8','67','CHINCA'],
            ['8','67','CHONTADURO'],
            ['8','67','CHUMUNDÉ'],
            ['8','67','LAGARTO'],
            ['8','67','LA UNIÓN'],
            ['8','67','MAJUA'],
            ['8','67','MONTALVO (CAB. EN HORQUETA)'],
            ['8','67','RÍO VERDE'],
            ['8','67','ROCAFUERTE'],
            ['8','67','SAN MATEO'],
            ['8','67','SÚA (CAB. EN LA BOCANA)'],
            ['8','67','TABIAZO'],
            ['8','67','TACHINA'],
            ['8','67','TONCHIGÜE'],
            ['8','67','VUELTA LARGA'],
            ['8','68','VALDEZ (LIMONES)'],
            ['8','68','ANCHAYACU'],
            ['8','68','ATAHUALPA (CAB. EN CAMARONES)'],
            ['8','68','BORBÓN'],
            ['8','68','LA TOLA'],
            ['8','68','LUIS VARGAS TORRES (CAB. EN PLAYA DE ORO)'],
            ['8','68','MALDONADO'],
            ['8','68','PAMPANAL DE BOLÍVAR'],
            ['8','68','SAN FRANCISCO DE ONZOLE'],
            ['8','68','SANTO DOMINGO DE ONZOLE'],
            ['8','68','SELVA ALEGRE'],
            ['8','68','TELEMBÍ'],
            ['8','68','COLÓN ELOY DEL MARÍA'],
            ['8','68','SAN JOSÉ DE CAYAPAS'],
            ['8','68','TIMBIRÉ'],
            ['8','69','MUISNE'],
            ['8','69','BOLÍVAR'],
            ['8','69','DAULE'],
            ['8','69','GALERA'],
            ['8','69','QUINGUE (OLMEDO PERDOMO FRANCO)'],
            ['8','69','SALIMA'],
            ['8','69','SAN FRANCISCO'],
            ['8','69','SAN GREGORIO'],
            ['8','69','SAN JOSÉ DE CHAMANGA (CAB.EN CHAMANGA)'],
            ['8','70','ROSA ZÁRATE (QUININDÉ)'],
            ['8','70','CUBE'],
            ['8','70','CHURA (CHANCAMA) (CAB. EN EL YERBERO)'],
            ['8','70','MALIMPIA'],
            ['8','70','VICHE'],
            ['8','70','LA UNIÓN'],
            ['8','71','SAN LORENZO'],
            ['8','71','ALTO TAMBO (CAB. EN GUADUAL)'],
            ['8','71','ANCÓN (PICHANGAL) (CAB. EN PALMA REAL)'],
            ['8','71','CALDERÓN'],
            ['8','71','CARONDELET'],
            ['8','71','5 DE JUNIO (CAB. EN UIMBI)'],
            ['8','71','CONCEPCIÓN'],
            ['8','71','MATAJE (CAB. EN SANTANDER)'],
            ['8','71','SAN JAVIER DE CACHAVÍ (CAB. EN SAN JAVIER)'],
            ['8','71','SANTA RITA'],
            ['8','71','TAMBILLO'],
            ['8','71','TULULBÍ (CAB. EN RICAURTE)'],
            ['8','71','URBINA'],
            ['8','72','ATACAMES'],
            ['8','72','LA UNIÓN'],
            ['8','72','SÚA (CAB. EN LA BOCANA)'],
            ['8','72','TONCHIGÜE'],
            ['8','72','TONSUPA'],
            ['8','73','RIOVERDE'],
            ['8','73','CHONTADURO'],
            ['8','73','CHUMUNDÉ'],
            ['8','73','LAGARTO'],
            ['8','73','MONTALVO (CAB. EN HORQUETA)'],
            ['8','73','ROCAFUERTE'],
            ['8','74','LA CONCORDIA'],
            ['8','74','MONTERREY'],
            ['8','74','LA VILLEGAS'],
            ['8','74','PLAN PILOTO'],
            ['9','75','AYACUCHO'],
            ['9','75','BOLÍVAR (SAGRARIO)'],
            ['9','75','CARBO (CONCEPCIÓN)'],
            ['9','75','FEBRES CORDERO'],
            ['9','75','GARCÍA MORENO'],
            ['9','75','LETAMENDI'],
            ['9','75','NUEVE DE OCTUBRE'],
            ['9','75','OLMEDO (SAN ALEJO)'],
            ['9','75','ROCA'],
            ['9','75','ROCAFUERTE'],
            ['9','75','SUCRE'],
            ['9','75','TARQUI'],
            ['9','75','URDANETA'],
            ['9','75','XIMENA'],
            ['9','75','PASCUALES'],
            ['9','75','GUAYAQUIL'],
            ['9','75','CHONGÓN'],
            ['9','75','JUAN GÓMEZ RENDÓN (PROGRESO)'],
            ['9','75','MORRO'],
            ['9','75','PLAYAS (GRAL. VILLAMIL)'],
            ['9','75','POSORJA'],
            ['9','75','PUNÁ'],
            ['9','75','TENGUEL'],
            ['9','76','ALFREDO BAQUERIZO MORENO (JUJÁN)'],
            ['9','77','BALAO'],
            ['9','78','BALZAR'],
            ['9','79','COLIMES'],
            ['9','79','SAN JACINTO'],
            ['9','80','DAULE'],
            ['9','80','LA AURORA (SATÉLITE)'],
            ['9','80','BANIFE'],
            ['9','80','EMILIANO CAICEDO MARCOS'],
            ['9','80','MAGRO'],
            ['9','80','PADRE JUAN BAUTISTA AGUIRRE'],
            ['9','80','SANTA CLARA'],
            ['9','80','VICENTE PIEDRAHITA'],
            ['9','80','ISIDRO AYORA (SOLEDAD)'],
            ['9','80','JUAN BAUTISTA AGUIRRE (LOS TINTOS)'],
            ['9','80','LAUREL'],
            ['9','80','LIMONAL'],
            ['9','80','LOMAS DE SARGENTILLO'],
            ['9','80','LOS LOJAS (ENRIQUE BAQUERIZO MORENO)'],
            ['9','80','PIEDRAHITA (NOBOL)'],
            ['9','81','ELOY ALFARO (DURÁN)'],
            ['9','81','EL RECREO'],
            ['9','82','VELASCO IBARRA (EL EMPALME)'],
            ['9','82','GUAYAS (PUEBLO NUEVO)'],
            ['9','82','EL ROSARIO'],
            ['9','83','EL TRIUNFO'],
            ['9','84','MILAGRO'],
            ['9','84','CHOBO'],
            ['9','84','GENERAL ELIZALDE (BUCAY)'],
            ['9','84','MARISCAL SUCRE (HUAQUES)'],
            ['9','84','ROBERTO ASTUDILLO (CAB. EN CRUCE DE VENECIA)'],
            ['9','85','NARANJAL'],
            ['9','85','JESÚS MARÍA'],
            ['9','85','SAN CARLOS'],
            ['9','85','SANTA ROSA DE FLANDES'],
            ['9','85','TAURA'],
            ['9','86','NARANJITO'],
            ['9','87','PALESTINA'],
            ['9','88','PEDRO CARBO'],
            ['9','88','VALLE DE LA VIRGEN'],
            ['9','88','SABANILLA'],
            ['9','89','SAMBORONDÓN'],
            ['9','89','LA PUNTILLA (SATÉLITE)'],
            ['9','89','TARIFA'],
            ['9','90','SANTA LUCÍA'],
            ['9','91','BOCANA'],
            ['9','91','CANDILEJOS'],
            ['9','91','CENTRAL'],
            ['9','91','PARAÍSO'],
            ['9','91','SAN MATEO'],
            ['9','91','EL SALITRE (LAS RAMAS)'],
            ['9','91','GRAL. VERNAZA (DOS ESTEROS)'],
            ['9','91','LA VICTORIA (ÑAUZA)'],
            ['9','91','JUNQUILLAL'],
            ['9','92','SAN JACINTO DE YAGUACHI'],
            ['9','92','CRNEL. LORENZO DE GARAICOA (PEDREGAL)'],
            ['9','92','CRNEL. MARCELINO MARIDUEÑA (SAN CARLOS)'],
            ['9','92','GRAL. PEDRO J. MONTERO (BOLICHE)'],
            ['9','92','SIMÓN BOLÍVAR'],
            ['9','92','YAGUACHI VIEJO (CONE)'],
            ['9','92','VIRGEN DE FÁTIMA'],
            ['9','93','GENERAL VILLAMIL (PLAYAS)'],
            ['9','94','SIMÓN BOLÍVAR'],
            ['9','94','CRNEL.LORENZO DE GARAICOA (PEDREGAL)'],
            ['9','95','CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)'],
            ['9','96','LOMAS DE SARGENTILLO'],
            ['9','96','ISIDRO AYORA (SOLEDAD)'],
            ['9','97','NARCISA DE JESÚS'],
            ['9','98','GENERAL ANTONIO ELIZALDE (BUCAY)'],
            ['9','99','ISIDRO AYORA'],
            ['10','100','CARANQUI'],
            ['10','100','GUAYAQUIL DE ALPACHACA'],
            ['10','100','SAGRARIO'],
            ['10','100','SAN FRANCISCO'],
            ['10','100','LA DOLOROSA DEL PRIORATO'],
            ['10','100','SAN MIGUEL DE IBARRA'],
            ['10','100','AMBUQUÍ'],
            ['10','100','ANGOCHAGUA'],
            ['10','100','CAROLINA'],
            ['10','100','LA ESPERANZA'],
            ['10','100','LITA'],
            ['10','100','SALINAS'],
            ['10','100','SAN ANTONIO'],
            ['10','101','ANDRADE MARÍN (LOURDES)'],
            ['10','101','ATUNTAQUI'],
            ['10','101','IMBAYA (SAN LUIS DE COBUENDO)'],
            ['10','101','SAN FRANCISCO DE NATABUELA'],
            ['10','101','SAN JOSÉ DE CHALTURA'],
            ['10','101','SAN ROQUE'],
            ['10','102','SAGRARIO'],
            ['10','102','SAN FRANCISCO'],
            ['10','102','COTACACHI'],
            ['10','102','APUELA'],
            ['10','102','GARCÍA MORENO (LLURIMAGUA)'],
            ['10','102','IMANTAG'],
            ['10','102','PEÑAHERRERA'],
            ['10','102','PLAZA GUTIÉRREZ (CALVARIO)'],
            ['10','102','QUIROGA'],
            ['10','102','6 DE JULIO DE CUELLAJE (CAB. EN CUELLAJE)'],
            ['10','102','VACAS GALINDO (EL CHURO) (CAB.EN SAN MIGUEL ALTO'],
            ['10','103','JORDÁN'],
            ['10','103','SAN LUIS'],
            ['10','103','OTAVALO'],
            ['10','103','DR. MIGUEL EGAS CABEZAS (PEGUCHE)'],
            ['10','103','EUGENIO ESPEJO (CALPAQUÍ)'],
            ['10','103','GONZÁLEZ SUÁREZ'],
            ['10','103','PATAQUÍ'],
            ['10','103','SAN JOSÉ DE QUICHINCHE'],
            ['10','103','SAN JUAN DE ILUMÁN'],
            ['10','103','SAN PABLO'],
            ['10','103','SAN RAFAEL'],
            ['10','103','SELVA ALEGRE (CAB.EN SAN MIGUEL DE PAMPLONA)'],
            ['10','104','PIMAMPIRO'],
            ['10','104','CHUGÁ'],
            ['10','104','MARIANO ACOSTA'],
            ['10','104','SAN FRANCISCO DE SIGSIPAMBA'],
            ['10','105','URCUQUÍ CABECERA CANTONAL'],
            ['10','105','CAHUASQUÍ'],
            ['10','105','LA MERCED DE BUENOS AIRES'],
            ['10','105','PABLO ARENAS'],
            ['10','105','SAN BLAS'],
            ['10','105','TUMBABIRO'],
            ['11','106','EL SAGRARIO'],
            ['11','106','SAN SEBASTIÁN'],
            ['11','106','SUCRE'],
            ['11','106','VALLE'],
            ['11','106','LOJA'],
            ['11','106','CHANTACO'],
            ['11','106','CHUQUIRIBAMBA'],
            ['11','106','EL CISNE'],
            ['11','106','GUALEL'],
            ['11','106','JIMBILLA'],
            ['11','106','MALACATOS (VALLADOLID)'],
            ['11','106','SAN LUCAS'],
            ['11','106','SAN PEDRO DE VILCABAMBA'],
            ['11','106','SANTIAGO'],
            ['11','106','TAQUIL (MIGUEL RIOFRÍO)'],
            ['11','106','VILCABAMBA (VICTORIA)'],
            ['11','106','YANGANA (ARSENIO CASTILLO)'],
            ['11','106','QUINARA'],
            ['11','107','CARIAMANGA'],
            ['11','107','CHILE'],
            ['11','107','SAN VICENTE'],
            ['11','107','COLAISACA'],
            ['11','107','EL LUCERO'],
            ['11','107','UTUANA'],
            ['11','107','SANGUILLÍN'],
            ['11','108','CATAMAYO'],
            ['11','108','SAN JOSÉ'],
            ['11','108','CATAMAYO (LA TOMA)'],
            ['11','108','EL TAMBO'],
            ['11','108','GUAYQUICHUMA'],
            ['11','108','SAN PEDRO DE LA BENDITA'],
            ['11','108','ZAMBI'],
            ['11','109','CELICA'],
            ['11','109','CRUZPAMBA (CAB. EN CARLOS BUSTAMANTE)'],
            ['11','109','CHAQUINAL'],
            ['11','109','12 DE DICIEMBRE (CAB. EN ACHIOTES)'],
            ['11','109','PINDAL (FEDERICO PÁEZ)'],
            ['11','109','POZUL (SAN JUAN DE POZUL)'],
            ['11','109','SABANILLA'],
            ['11','109','TNTE. MAXIMILIANO RODRÍGUEZ LOAIZA'],
            ['11','110','CHAGUARPAMBA'],
            ['11','110','BUENAVISTA'],
            ['11','110','EL ROSARIO'],
            ['11','110','SANTA RUFINA'],
            ['11','110','AMARILLOS'],
            ['11','111','AMALUZA'],
            ['11','111','BELLAVISTA'],
            ['11','111','JIMBURA'],
            ['11','111','SANTA TERESITA'],
            ['11','111','27 DE ABRIL (CAB. EN LA NARANJA)'],
            ['11','111','EL INGENIO'],
            ['11','111','EL AIRO'],
            ['11','112','GONZANAMÁ'],
            ['11','112','CHANGAIMINA (LA LIBERTAD)'],
            ['11','112','FUNDOCHAMBA'],
            ['11','112','NAMBACOLA'],
            ['11','112','PURUNUMA (EGUIGUREN)'],
            ['11','112','QUILANGA (LA PAZ)'],
            ['11','112','SACAPALCA'],
            ['11','112','SAN ANTONIO DE LAS ARADAS (CAB. EN LAS ARADAS)'],
            ['11','113','GENERAL ELOY ALFARO (SAN SEBASTIÁN)'],
            ['11','113','MACARÁ (MANUEL ENRIQUE RENGEL SUQUILANDA)'],
            ['11','113','MACARÁ'],
            ['11','113','LARAMA'],
            ['11','113','LA VICTORIA'],
            ['11','113','SABIANGO (LA CAPILLA)'],
            ['11','114','CATACOCHA'],
            ['11','114','LOURDES'],
            ['11','114','CANGONAMÁ'],
            ['11','114','GUACHANAMÁ'],
            ['11','114','LA TINGUE'],
            ['11','114','LAURO GUERRERO'],
            ['11','114','OLMEDO (SANTA BÁRBARA)'],
            ['11','114','ORIANGA'],
            ['11','114','SAN ANTONIO'],
            ['11','114','CASANGA'],
            ['11','114','YAMANA'],
            ['11','115','ALAMOR'],
            ['11','115','CIANO'],
            ['11','115','EL ARENAL'],
            ['11','115','EL LIMO (MARIANA DE JESÚS)'],
            ['11','115','MERCADILLO'],
            ['11','115','VICENTINO'],
            ['11','116','SARAGURO'],
            ['11','116','EL PARAÍSO DE CELÉN'],
            ['11','116','EL TABLÓN'],
            ['11','116','LLUZHAPA'],
            ['11','116','MANÚ'],
            ['11','116','SAN ANTONIO DE QUMBE (CUMBE)'],
            ['11','116','SAN PABLO DE TENTA'],
            ['11','116','SAN SEBASTIÁN DE YÚLUC'],
            ['11','116','SELVA ALEGRE'],
            ['11','116','URDANETA (PAQUISHAPA)'],
            ['11','116','SUMAYPAMBA'],
            ['11','117','SOZORANGA'],
            ['11','117','NUEVA FÁTIMA'],
            ['11','117','TACAMOROS'],
            ['11','118','ZAPOTILLO'],
            ['11','118','MANGAHURCO (CAZADEROS)'],
            ['11','118','GARZAREAL'],
            ['11','118','LIMONES'],
            ['11','118','PALETILLAS'],
            ['11','118','BOLASPAMBA'],
            ['11','119','PINDAL'],
            ['11','119','CHAQUINAL'],
            ['11','119','12 DE DICIEMBRE (CAB.EN ACHIOTES)'],
            ['11','119','MILAGROS'],
            ['11','120','QUILANGA'],
            ['11','120','FUNDOCHAMBA'],
            ['11','120','SAN ANTONIO DE LAS ARADAS (CAB. EN LAS ARADAS)'],
            ['11','121','OLMEDO'],
            ['11','121','LA TINGUE'],
            ['12','122','CLEMENTE BAQUERIZO'],
            ['12','122','DR. CAMILO PONCE'],
            ['12','122','BARREIRO'],
            ['12','122','EL SALTO'],
            ['12','122','BABAHOYO'],
            ['12','122','BARREIRO (SANTA RITA)'],
            ['12','122','CARACOL'],
            ['12','122','FEBRES CORDERO (LAS JUNTAS)'],
            ['12','122','PIMOCHA'],
            ['12','122','LA UNIÓN'],
            ['12','123','BABA'],
            ['12','123','GUARE'],
            ['12','123','ISLA DE BEJUCAL'],
            ['12','124','MONTALVO'],
            ['12','125','PUEBLOVIEJO'],
            ['12','125','PUERTO PECHICHE'],
            ['12','125','SAN JUAN'],
            ['12','126','QUEVEDO'],
            ['12','126','SAN CAMILO'],
            ['12','126','SAN JOSÉ'],
            ['12','126','GUAYACÁN'],
            ['12','126','NICOLÁS INFANTE DÍAZ'],
            ['12','126','SAN CRISTÓBAL'],
            ['12','126','SIETE DE OCTUBRE'],
            ['12','126','24 DE MAYO'],
            ['12','126','VENUS DEL RÍO QUEVEDO'],
            ['12','126','VIVA ALFARO'],
            ['12','126','BUENA FÉ'],
            ['12','126','MOCACHE'],
            ['12','126','SAN CARLOS'],
            ['12','126','VALENCIA'],
            ['12','126','LA ESPERANZA'],
            ['12','127','CATARAMA'],
            ['12','127','RICAURTE'],
            ['12','128','10 DE NOVIEMBRE'],
            ['12','128','VENTANAS'],
            ['12','128','QUINSALOMA'],
            ['12','128','ZAPOTAL'],
            ['12','128','CHACARITA'],
            ['12','128','LOS ÁNGELES'],
            ['12','129','VINCES'],
            ['12','129','ANTONIO SOTOMAYOR (CAB. EN PLAYAS DE VINCES)'],
            ['12','129','PALENQUE'],
            ['12','130','PALENQUE'],
            ['12','131','SAN JACINTO DE BUENA FÉ'],
            ['12','131','7 DE AGOSTO'],
            ['12','131','11 DE OCTUBRE'],
            ['12','131','PATRICIA PILAR'],
            ['12','132','VALENCIA'],
            ['12','133','MOCACHE'],
            ['12','134','QUINSALOMA'],
            ['13','135','PORTOVIEJO'],
            ['13','135','12 DE MARZO'],
            ['13','135','COLÓN'],
            ['13','135','PICOAZÁ'],
            ['13','135','SAN PABLO'],
            ['13','135','ANDRÉS DE VERA'],
            ['13','135','FRANCISCO PACHECO'],
            ['13','135','18 DE OCTUBRE'],
            ['13','135','SIMÓN BOLÍVAR'],
            ['13','135','ABDÓN CALDERÓN (SAN FRANCISCO)'],
            ['13','135','ALHAJUELA (BAJO GRANDE)'],
            ['13','135','CRUCITA'],
            ['13','135','PUEBLO NUEVO'],
            ['13','135','RIOCHICO (RÍO CHICO)'],
            ['13','135','SAN PLÁCIDO'],
            ['13','135','CHIRIJOS'],
            ['13','136','CALCETA'],
            ['13','136','MEMBRILLO'],
            ['13','136','QUIROGA'],
            ['13','137','CHONE'],
            ['13','137','SANTA RITA'],
            ['13','137','BOYACÁ'],
            ['13','137','CANUTO'],
            ['13','137','CONVENTO'],
            ['13','137','CHIBUNGA'],
            ['13','137','ELOY ALFARO'],
            ['13','137','RICAURTE'],
            ['13','137','SAN ANTONIO'],
            ['13','138','EL CARMEN'],
            ['13','138','4 DE DICIEMBRE'],
            ['13','138','WILFRIDO LOOR MOREIRA (MAICITO)'],
            ['13','138','SAN PEDRO DE SUMA'],
            ['13','139','FLAVIO ALFARO'],
            ['13','139','SAN FRANCISCO DE NOVILLO (CAB. EN'],
            ['13','139','ZAPALLO'],
            ['13','140','DR. MIGUEL MORÁN LUCIO'],
            ['13','140','MANUEL INOCENCIO PARRALES Y GUALE'],
            ['13','140','SAN LORENZO DE JIPIJAPA'],
            ['13','140','JIPIJAPA'],
            ['13','140','AMÉRICA'],
            ['13','140','EL ANEGADO (CAB. EN ELOY ALFARO)'],
            ['13','140','JULCUY'],
            ['13','140','LA UNIÓN'],
            ['13','140','MACHALILLA'],
            ['13','140','MEMBRILLAL'],
            ['13','140','PEDRO PABLO GÓMEZ'],
            ['13','140','PUERTO DE CAYO'],
            ['13','140','PUERTO LÓPEZ'],
            ['13','141','JUNÍN'],
            ['13','142','LOS ESTEROS'],
            ['13','142','MANTA'],
            ['13','142','SAN MATEO'],
            ['13','142','TARQUI'],
            ['13','142','ELOY ALFARO'],
            ['13','142','SAN LORENZO'],
            ['13','142','SANTA MARIANITA (BOCA DE PACOCHE)'],
            ['13','143','ANIBAL SAN ANDRÉS'],
            ['13','143','MONTECRISTI'],
            ['13','143','EL COLORADO'],
            ['13','143','GENERAL ELOY ALFARO'],
            ['13','143','LEONIDAS PROAÑO'],
            ['13','143','JARAMIJÓ'],
            ['13','143','LA PILA'],
            ['13','144','PAJÁN'],
            ['13','144','CAMPOZANO (LA PALMA DE PAJÁN)'],
            ['13','144','CASCOL'],
            ['13','144','GUALE'],
            ['13','144','LASCANO'],
            ['13','145','PICHINCHA'],
            ['13','145','BARRAGANETE'],
            ['13','145','SAN SEBASTIÁN'],
            ['13','146','ROCAFUERTE'],
            ['13','147','SANTA ANA'],
            ['13','147','LODANA'],
            ['13','147','SANTA ANA DE VUELTA LARGA'],
            ['13','147','AYACUCHO'],
            ['13','147','HONORATO VÁSQUEZ (CAB. EN VÁSQUEZ)'],
            ['13','147','LA UNIÓN'],
            ['13','147','OLMEDO'],
            ['13','147','SAN PABLO (CAB. EN PUEBLO NUEVO)'],
            ['13','148','BAHÍA DE CARÁQUEZ'],
            ['13','148','LEONIDAS PLAZA GUTIÉRREZ'],
            ['13','148','CANOA'],
            ['13','148','COJIMÍES'],
            ['13','148','CHARAPOTÓ'],
            ['13','148','10 DE AGOSTO'],
            ['13','148','JAMA'],
            ['13','148','PEDERNALES'],
            ['13','148','SAN ISIDRO'],
            ['13','148','SAN VICENTE'],
            ['13','149','TOSAGUA'],
            ['13','149','BACHILLERO'],
            ['13','149','ANGEL PEDRO GILER (LA ESTANCILLA)'],
            ['13','150','SUCRE'],
            ['13','150','BELLAVISTA'],
            ['13','150','NOBOA'],
            ['13','150','ARQ. SIXTO DURÁN BALLÉN'],
            ['13','151','PEDERNALES'],
            ['13','151','COJIMÍES'],
            ['13','151','10 DE AGOSTO'],
            ['13','151','ATAHUALPA'],
            ['13','152','OLMEDO'],
            ['13','153','PUERTO LÓPEZ'],
            ['13','153','MACHALILLA'],
            ['13','153','SALANGO'],
            ['13','154','JAMA'],
            ['13','155','JARAMIJÓ'],
            ['13','156','SAN VICENTE'],
            ['13','156','CANOA'],
            ['14','157','MACAS'],
            ['14','157','ALSHI (CAB. EN 9 DE OCTUBRE)'],
            ['14','157','CHIGUAZA'],
            ['14','157','GENERAL PROAÑO'],
            ['14','157','HUASAGA (CAB.EN WAMPUIK)'],
            ['14','157','MACUMA'],
            ['14','157','SAN ISIDRO'],
            ['14','157','SEVILLA DON BOSCO'],
            ['14','157','SINAÍ'],
            ['14','157','TAISHA'],
            ['14','157','ZUÑA (ZÚÑAC)'],
            ['14','157','TUUTINENTZA'],
            ['14','157','CUCHAENTZA'],
            ['14','157','SAN JOSÉ DE MORONA'],
            ['14','157','RÍO BLANCO'],
            ['14','158','GUALAQUIZA'],
            ['14','158','MERCEDES MOLINA'],
            ['14','158','AMAZONAS (ROSARIO DE CUYES)'],
            ['14','158','BERMEJOS'],
            ['14','158','BOMBOIZA'],
            ['14','158','CHIGÜINDA'],
            ['14','158','EL ROSARIO'],
            ['14','158','NUEVA TARQUI'],
            ['14','158','SAN MIGUEL DE CUYES'],
            ['14','158','EL IDEAL'],
            ['14','159','GENERAL LEONIDAS PLAZA GUTIÉRREZ (LIMÓN)'],
            ['14','159','INDANZA'],
            ['14','159','PAN DE AZÚCAR'],
            ['14','159','SAN ANTONIO (CAB. EN SAN ANTONIO CENTRO'],
            ['14','159','SAN CARLOS DE LIMÓN (SAN CARLOS DEL'],
            ['14','159','SAN JUAN BOSCO'],
            ['14','159','SAN MIGUEL DE CONCHAY'],
            ['14','159','SANTA SUSANA DE CHIVIAZA (CAB. EN CHIVIAZA)'],
            ['14','159','YUNGANZA (CAB. EN EL ROSARIO)'],
            ['14','160','PALORA (METZERA)'],
            ['14','160','ARAPICOS'],
            ['14','160','CUMANDÁ (CAB. EN COLONIA AGRÍCOLA SEVILLA DEL ORO)'],
            ['14','160','HUAMBOYA'],
            ['14','160','SANGAY (CAB. EN NAYAMANACA)'],
            ['14','161','SANTIAGO DE MÉNDEZ'],
            ['14','161','COPAL'],
            ['14','161','CHUPIANZA'],
            ['14','161','PATUCA'],
            ['14','161','SAN LUIS DE EL ACHO (CAB. EN EL ACHO)'],
            ['14','161','SANTIAGO'],
            ['14','161','TAYUZA'],
            ['14','161','SAN FRANCISCO DE CHINIMBIMI'],
            ['14','162','SUCÚA'],
            ['14','162','ASUNCIÓN'],
            ['14','162','HUAMBI'],
            ['14','162','LOGROÑO'],
            ['14','162','YAUPI'],
            ['14','162','SANTA MARIANITA DE JESÚS'],
            ['14','163','HUAMBOYA'],
            ['14','163','CHIGUAZA'],
            ['14','163','PABLO SEXTO'],
            ['14','164','SAN JUAN BOSCO'],
            ['14','164','PAN DE AZÚCAR'],
            ['14','164','SAN CARLOS DE LIMÓN'],
            ['14','164','SAN JACINTO DE WAKAMBEIS'],
            ['14','164','SANTIAGO DE PANANZA'],
            ['14','165','TAISHA'],
            ['14','165','HUASAGA (CAB. EN WAMPUIK)'],
            ['14','165','MACUMA'],
            ['14','165','TUUTINENTZA'],
            ['14','165','PUMPUENTSA'],
            ['14','166','LOGROÑO'],
            ['14','166','YAUPI'],
            ['14','166','SHIMPIS'],
            ['14','167','PABLO SEXTO'],
            ['14','168','SANTIAGO'],
            ['14','168','SAN JOSÉ DE MORONA'],
            ['15','169','TENA'],
            ['15','169','AHUANO'],
            ['15','169','CARLOS JULIO AROSEMENA TOLA (ZATZA-YACU)'],
            ['15','169','CHONTAPUNTA'],
            ['15','169','PANO'],
            ['15','169','PUERTO MISAHUALLI'],
            ['15','169','PUERTO NAPO'],
            ['15','169','TÁLAG'],
            ['15','169','SAN JUAN DE MUYUNA'],
            ['15','170','ARCHIDONA'],
            ['15','170','AVILA'],
            ['15','170','COTUNDO'],
            ['15','170','LORETO'],
            ['15','170','SAN PABLO DE USHPAYACU'],
            ['15','170','PUERTO MURIALDO'],
            ['15','171','EL CHACO'],
            ['15','171','GONZALO DíAZ DE PINEDA (EL BOMBÓN)'],
            ['15','171','LINARES'],
            ['15','171','OYACACHI'],
            ['15','171','SANTA ROSA'],
            ['15','171','SARDINAS'],
            ['15','172','BAEZA'],
            ['15','172','COSANGA'],
            ['15','172','CUYUJA'],
            ['15','172','PAPALLACTA'],
            ['15','172','SAN FRANCISCO DE BORJA (VIRGILIO DÁVILA)'],
            ['15','172','SAN JOSÉ DEL PAYAMINO'],
            ['15','172','SUMACO'],
            ['15','173','CARLOS JULIO AROSEMENA TOLA'],
            ['16','174','PUYO'],
            ['16','174','ARAJUNO'],
            ['16','174','CANELOS'],
            ['16','174','CURARAY'],
            ['16','174','DIEZ DE AGOSTO'],
            ['16','174','FÁTIMA'],
            ['16','174','MONTALVO (ANDOAS)'],
            ['16','174','POMONA'],
            ['16','174','RÍO CORRIENTES'],
            ['16','174','RÍO TIGRE'],
            ['16','174','SANTA CLARA'],
            ['16','174','SARAYACU'],
            ['16','174','SIMÓN BOLÍVAR (CAB. EN MUSHULLACTA)'],
            ['16','174','TARQUI'],
            ['16','174','TENIENTE HUGO ORTIZ'],
            ['16','174','VERACRUZ (INDILLAMA) (CAB. EN INDILLAMA)'],
            ['16','174','EL TRIUNFO'],
            ['16','175','MERA'],
            ['16','175','MADRE TIERRA'],
            ['16','175','SHELL'],
            ['16','176','SANTA CLARA'],
            ['16','176','SAN JOSÉ'],
            ['16','177','ARAJUNO'],
            ['16','177','CURARAY'],
            ['17','178','BELISARIO QUEVEDO'],
            ['17','178','CARCELÉN'],
            ['17','178','CENTRO HISTÓRICO'],
            ['17','178','COCHAPAMBA'],
            ['17','178','COMITÉ DEL PUEBLO'],
            ['17','178','COTOCOLLAO'],
            ['17','178','CHILIBULO'],
            ['17','178','CHILLOGALLO'],
            ['17','178','CHIMBACALLE'],
            ['17','178','EL CONDADO'],
            ['17','178','GUAMANÍ'],
            ['17','178','IÑAQUITO'],
            ['17','178','ITCHIMBÍA'],
            ['17','178','JIPIJAPA'],
            ['17','178','KENNEDY'],
            ['17','178','LA ARGELIA'],
            ['17','178','LA CONCEPCIÓN'],
            ['17','178','LA ECUATORIANA'],
            ['17','178','LA FERROVIARIA'],
            ['17','178','LA LIBERTAD'],
            ['17','178','LA MAGDALENA'],
            ['17','178','LA MENA'],
            ['17','178','MARISCAL SUCRE'],
            ['17','178','PONCEANO'],
            ['17','178','PUENGASÍ'],
            ['17','178','QUITUMBE'],
            ['17','178','RUMIPAMBA'],
            ['17','178','SAN BARTOLO'],
            ['17','178','SAN ISIDRO DEL INCA'],
            ['17','178','SAN JUAN'],
            ['17','178','SOLANDA'],
            ['17','178','TURUBAMBA'],
            ['17','178','QUITO DISTRITO METROPOLITANO'],
            ['17','178','ALANGASÍ'],
            ['17','178','AMAGUAÑA'],
            ['17','178','ATAHUALPA'],
            ['17','178','CALACALÍ'],
            ['17','178','CALDERÓN'],
            ['17','178','CONOCOTO'],
            ['17','178','CUMBAYÁ'],
            ['17','178','CHAVEZPAMBA'],
            ['17','178','CHECA'],
            ['17','178','EL QUINCHE'],
            ['17','178','GUALEA'],
            ['17','178','GUANGOPOLO'],
            ['17','178','GUAYLLABAMBA'],
            ['17','178','LA MERCED'],
            ['17','178','LLANO CHICO'],
            ['17','178','LLOA'],
            ['17','178','MINDO'],
            ['17','178','NANEGAL'],
            ['17','178','NANEGALITO'],
            ['17','178','NAYÓN'],
            ['17','178','NONO'],
            ['17','178','PACTO'],
            ['17','178','PEDRO VICENTE MALDONADO'],
            ['17','178','PERUCHO'],
            ['17','178','PIFO'],
            ['17','178','PÍNTAG'],
            ['17','178','POMASQUI'],
            ['17','178','PUÉLLARO'],
            ['17','178','PUEMBO'],
            ['17','178','SAN ANTONIO'],
            ['17','178','SAN JOSÉ DE MINAS'],
            ['17','178','SAN MIGUEL DE LOS BANCOS'],
            ['17','178','TABABELA'],
            ['17','178','TUMBACO'],
            ['17','178','YARUQUÍ'],
            ['17','178','ZAMBIZA'],
            ['17','178','PUERTO QUITO'],
            ['17','179','AYORA'],
            ['17','179','CAYAMBE'],
            ['17','179','JUAN MONTALVO'],
            ['17','179','ASCÁZUBI'],
            ['17','179','CANGAHUA'],
            ['17','179','OLMEDO (PESILLO)'],
            ['17','179','OTÓN'],
            ['17','179','SANTA ROSA DE CUZUBAMBA'],
            ['17','180','MACHACHI'],
            ['17','180','ALÓAG'],
            ['17','180','ALOASÍ'],
            ['17','180','CUTUGLAHUA'],
            ['17','180','EL CHAUPI'],
            ['17','180','MANUEL CORNEJO ASTORGA (TANDAPI)'],
            ['17','180','TAMBILLO'],
            ['17','180','UYUMBICHO'],
            ['17','181','TABACUNDO'],
            ['17','181','LA ESPERANZA'],
            ['17','181','MALCHINGUÍ'],
            ['17','181','TOCACHI'],
            ['17','181','TUPIGACHI'],
            ['17','182','SANGOLQUÍ'],
            ['17','182','SAN PEDRO DE TABOADA'],
            ['17','182','SAN RAFAEL'],
            ['17','182','SANGOLQUI'],
            ['17','182','COTOGCHOA'],
            ['17','182','RUMIPAMBA'],
            ['17','183','SAN MIGUEL DE LOS BANCOS'],
            ['17','183','MINDO'],
            ['17','183','PEDRO VICENTE MALDONADO'],
            ['17','183','PUERTO QUITO'],
            ['17','184','PEDRO VICENTE MALDONADO'],
            ['17','185','PUERTO QUITO'],
            ['18','186','ATOCHA – FICOA'],
            ['18','186','CELIANO MONGE'],
            ['18','186','HUACHI CHICO'],
            ['18','186','HUACHI LORETO'],
            ['18','186','LA MERCED'],
            ['18','186','LA PENÍNSULA'],
            ['18','186','MATRIZ'],
            ['18','186','PISHILATA'],
            ['18','186','SAN FRANCISCO'],
            ['18','186','AMBATO'],
            ['18','186','AMBATILLO'],
            ['18','186','ATAHUALPA (CHISALATA)'],
            ['18','186','AUGUSTO N. MARTÍNEZ (MUNDUGLEO)'],
            ['18','186','CONSTANTINO FERNÁNDEZ (CAB. EN CULLITAHUA)'],
            ['18','186','HUACHI GRANDE'],
            ['18','186','IZAMBA'],
            ['18','186','JUAN BENIGNO VELA'],
            ['18','186','MONTALVO'],
            ['18','186','PASA'],
            ['18','186','PICAIGUA'],
            ['18','186','PILAGÜÍN (PILAHÜÍN)'],
            ['18','186','QUISAPINCHA (QUIZAPINCHA)'],
            ['18','186','SAN BARTOLOMÉ DE PINLLOG'],
            ['18','186','SAN FERNANDO (PASA SAN FERNANDO)'],
            ['18','186','SANTA ROSA'],
            ['18','186','TOTORAS'],
            ['18','186','CUNCHIBAMBA'],
            ['18','186','UNAMUNCHO'],
            ['18','187','BAÑOS DE AGUA SANTA'],
            ['18','187','LLIGUA'],
            ['18','187','RÍO NEGRO'],
            ['18','187','RÍO VERDE'],
            ['18','187','ULBA'],
            ['18','188','CEVALLOS'],
            ['18','189','MOCHA'],
            ['18','189','PINGUILÍ'],
            ['18','190','PATATE'],
            ['18','190','EL TRIUNFO'],
            ['18','190','LOS ANDES (CAB. EN POATUG)'],
            ['18','190','SUCRE (CAB. EN SUCRE-PATATE URCU)'],
            ['18','191','QUERO'],
            ['18','191','RUMIPAMBA'],
            ['18','191','YANAYACU - MOCHAPATA (CAB. EN YANAYACU)'],
            ['18','192','PELILEO'],
            ['18','192','PELILEO GRANDE'],
            ['18','192','BENÍTEZ (PACHANLICA)'],
            ['18','192','BOLÍVAR'],
            ['18','192','COTALÓ'],
            ['18','192','CHIQUICHA (CAB. EN CHIQUICHA GRANDE)'],
            ['18','192','EL ROSARIO (RUMICHACA)'],
            ['18','192','GARCÍA MORENO (CHUMAQUI)'],
            ['18','192','GUAMBALÓ (HUAMBALÓ)'],
            ['18','192','SALASACA'],
            ['18','193','CIUDAD NUEVA'],
            ['18','193','PÍLLARO'],
            ['18','193','BAQUERIZO MORENO'],
            ['18','193','EMILIO MARÍA TERÁN (RUMIPAMBA)'],
            ['18','193','MARCOS ESPINEL (CHACATA)'],
            ['18','193','PRESIDENTE URBINA (CHAGRAPAMBA -PATZUCUL)'],
            ['18','193','SAN ANDRÉS'],
            ['18','193','SAN JOSÉ DE POALÓ'],
            ['18','193','SAN MIGUELITO'],
            ['18','194','TISALEO'],
            ['18','194','QUINCHICOTO'],
            ['19','195','EL LIMÓN'],
            ['19','195','ZAMORA'],
            ['19','195','CUMBARATZA'],
            ['19','195','GUADALUPE'],
            ['19','195','IMBANA (LA VICTORIA DE IMBANA)'],
            ['19','195','PAQUISHA'],
            ['19','195','SABANILLA'],
            ['19','195','TIMBARA'],
            ['19','195','ZUMBI'],
            ['19','195','SAN CARLOS DE LAS MINAS'],
            ['19','196','ZUMBA'],
            ['19','196','CHITO'],
            ['19','196','EL CHORRO'],
            ['19','196','EL PORVENIR DEL CARMEN'],
            ['19','196','LA CHONTA'],
            ['19','196','PALANDA'],
            ['19','196','PUCAPAMBA'],
            ['19','196','SAN FRANCISCO DEL VERGEL'],
            ['19','196','VALLADOLID'],
            ['19','196','SAN ANDRÉS'],
            ['19','197','GUAYZIMI'],
            ['19','197','ZURMI'],
            ['19','197','NUEVO PARAÍSO'],
            ['19','198','28 DE MAYO (SAN JOSÉ DE YACUAMBI)'],
            ['19','198','LA PAZ'],
            ['19','198','TUTUPALI'],
            ['19','199','YANTZAZA (YANZATZA)'],
            ['19','199','CHICAÑA'],
            ['19','199','EL PANGUI'],
            ['19','199','LOS ENCUENTROS'],
            ['19','200','EL PANGUI'],
            ['19','200','EL GUISME'],
            ['19','200','PACHICUTZA'],
            ['19','200','TUNDAYME'],
            ['19','201','ZUMBI'],
            ['19','201','PAQUISHA'],
            ['19','201','TRIUNFO-DORADO'],
            ['19','201','PANGUINTZA'],
            ['19','202','PALANDA'],
            ['19','202','EL PORVENIR DEL CARMEN'],
            ['19','202','SAN FRANCISCO DEL VERGEL'],
            ['19','202','VALLADOLID'],
            ['19','202','LA CANELA'],
            ['19','203','PAQUISHA'],
            ['19','203','BELLAVISTA'],
            ['19','203','NUEVO QUITO'],
            ['20','204','PUERTO BAQUERIZO MORENO'],
            ['20','204','EL PROGRESO'],
            ['20','204','A SANTA MARÍA (FLOREANA) (CAB. EN PTO. VELASCO IBARR'],
            ['20','205','PUERTO VILLAMIL'],
            ['20','205','TOMÁS DE BERLANGA (SANTO TOMÁS)'],
            ['20','206','PUERTO AYORA'],
            ['20','206','BELLAVISTA'],
            ['20','206','SANTA ROSA (INCLUYE LA ISLA BALTRA)'],
            ['21','207','NUEVA LOJA'],
            ['21','207','CUYABENO'],
            ['21','207','DURENO'],
            ['21','207','GENERAL FARFÁN'],
            ['21','207','TARAPOA'],
            ['21','207','EL ENO'],
            ['21','207','PACAYACU'],
            ['21','207','JAMBELÍ'],
            ['21','207','SANTA CECILIA'],
            ['21','207','AGUAS NEGRAS'],
            ['21','208','EL DORADO DE CASCALES'],
            ['21','208','EL REVENTADOR'],
            ['21','208','GONZALO PIZARRO'],
            ['21','208','LUMBAQUÍ'],
            ['21','208','PUERTO LIBRE'],
            ['21','208','SANTA ROSA DE SUCUMBÍOS'],
            ['21','209','PUERTO EL CARMEN DEL PUTUMAYO'],
            ['21','209','PALMA ROJA'],
            ['21','209','PUERTO BOLÍVAR (PUERTO MONTÚFAR)'],
            ['21','209','PUERTO RODRÍGUEZ'],
            ['21','209','SANTA ELENA'],
            ['21','210','SHUSHUFINDI'],
            ['21','210','LIMONCOCHA'],
            ['21','210','PAÑACOCHA'],
            ['21','210','SAN ROQUE (CAB. EN SAN VICENTE)'],
            ['21','210','SAN PEDRO DE LOS COFANES'],
            ['21','210','SIETE DE JULIO'],
            ['21','211','LA BONITA'],
            ['21','211','EL PLAYÓN DE SAN FRANCISCO'],
            ['21','211','LA SOFÍA'],
            ['21','211','ROSA FLORIDA'],
            ['21','211','SANTA BÁRBARA'],
            ['21','212','EL DORADO DE CASCALES'],
            ['21','212','SANTA ROSA DE SUCUMBÍOS'],
            ['21','212','SEVILLA'],
            ['21','213','TARAPOA'],
            ['21','213','CUYABENO'],
            ['21','213','AGUAS NEGRAS'],
            ['22','214','PUERTO FRANCISCO DE ORELLANA (EL COCA)'],
            ['22','214','DAYUMA'],
            ['22','214','TARACOA (NUEVA ESPERANZA: YUCA)'],
            ['22','214','ALEJANDRO LABAKA'],
            ['22','214','EL DORADO'],
            ['22','214','EL EDÉN'],
            ['22','214','GARCÍA MORENO'],
            ['22','214','INÉS ARANGO (CAB. EN WESTERN)'],
            ['22','214','LA BELLEZA'],
            ['22','214','NUEVO PARAÍSO (CAB. EN UNIÓN'],
            ['22','214','SAN JOSÉ DE GUAYUSA'],
            ['22','214','SAN LUIS DE ARMENIA'],
            ['22','215','TIPITINI'],
            ['22','215','NUEVO ROCAFUERTE'],
            ['22','215','CAPITÁN AUGUSTO RIVADENEYRA'],
            ['22','215','CONONACO'],
            ['22','215','SANTA MARÍA DE HUIRIRIMA'],
            ['22','215','TIPUTINI'],
            ['22','215','YASUNÍ'],
            ['22','216','LA JOYA DE LOS SACHAS'],
            ['22','216','ENOKANQUI'],
            ['22','216','POMPEYA'],
            ['22','216','SAN CARLOS'],
            ['22','216','SAN SEBASTIÁN DEL COCA'],
            ['22','216','LAGO SAN PEDRO'],
            ['22','216','RUMIPAMBA'],
            ['22','216','TRES DE NOVIEMBRE'],
            ['22','216','UNIÓN MILAGREÑA'],
            ['22','217','LORETO'],
            ['22','217','AVILA (CAB. EN HUIRUNO)'],
            ['22','217','PUERTO MURIALDO'],
            ['22','217','SAN JOSÉ DE PAYAMINO'],
            ['22','217','SAN JOSÉ DE DAHUANO'],
            ['22','217','SAN VICENTE DE HUATICOCHA'],
            ['23','218','ABRAHAM CALAZACÓN'],
            ['23','218','BOMBOLÍ'],
            ['23','218','CHIGUILPE'],
            ['23','218','RÍO TOACHI'],
            ['23','218','RÍO VERDE'],
            ['23','218','SANTO DOMINGO DE LOS COLORADOS'],
            ['23','218','ZARACAY'],
            ['23','218','ALLURIQUÍN'],
            ['23','218','PUERTO LIMÓN'],
            ['23','218','LUZ DE AMÉRICA'],
            ['23','218','SAN JACINTO DEL BÚA'],
            ['23','218','VALLE HERMOSO'],
            ['23','218','EL ESFUERZO'],
            ['23','218','SANTA MARÍA DEL TOACHI'],
            ['24','219','BALLENITA'],
            ['24','219','SANTA ELENA'],
            ['24','219','ATAHUALPA'],
            ['24','219','COLONCHE'],
            ['24','219','CHANDUY'],
            ['24','219','MANGLARALTO'],
            ['24','219','SIMÓN BOLÍVAR (JULIO MORENO)'],
            ['24','219','SAN JOSÉ DE ANCÓN'],
            ['24','220','LA LIBERTAD'],
            ['24','221','CARLOS ESPINOZA LARREA'],
            ['24','221','GRAL. ALBERTO ENRÍQUEZ GALLO'],
            ['24','221','VICENTE ROCAFUERTE'],
            ['24','221','SANTA ROSA'],
            ['24','221','SALINAS'],
            ['24','221','ANCONCITO'],
            ['24','221','JOSÉ LUIS TAMAYO (MUEY)']
        ];

        foreach ($Parroquias as $value) {
            Parroquia::create(['provincia_id' => $value[0],'canton_id' => $value[1],'nombre' => $value[2]]);
        }*/
    }
}
